# Generated by Django 3.0.5 on 2020-07-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_starter_app', '0004_auto_20200628_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount',
            field=models.FloatField(default='3000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='email',
            field=models.EmailField(default='slim@yahoo.com', max_length=254),
            preserve_default=False,
        ),
    ]
